#!/usr/bin/env python

import os
import subprocess
import argparse

USERNAME = "santatra"
IP = os.environ["IP_ADDR"]
REMOTE_HOME ="/home/santatra/k8s/k3d/nginx"
REMOTE_REF = f"{USERNAME}@{IP}"
REMOTE_HOME_REF = f'{REMOTE_REF}:{REMOTE_HOME}'

if IP is None or IP == "":
    print("Please set IP_ADDR environment variable")
    exit(1)


def test_ratsy():
    remote_nginx = "/var/ossec"
    cmd = "ssh -t {0} \"ls -lh {1}\"".format(
            REMOTE_REF,
            remote_nginx)
    subprocess.run(cmd, shell=True)
    exit(0)

def exec_on_remote(cmd, isRoot=True):
    rem_cmd = "sudo " + cmd if isRoot else cmd
    remote_cmd = "ssh -t {0} {1}".format(
            REMOTE_REF,
            rem_cmd
            )
    subprocess.run(remote_cmd, shell=True)


def sudo_fetch():
    remote_nginx_file = "/etc/nginx/sites-available/mojaloop"
    cmd = "rsync -aP {0} {1}".format(
            remote_nginx_file,
            REMOTE_HOME
            )
    exec_on_remote(cmd)

def main():
    targets = "mojaloop"

    # Set parser
    parser = argparse.ArgumentParser()
    parser.add_argument("--debug", help=f"Fanaovana test sy debug", action="store_true")
    parser.add_argument("--pull", help=f"Alaina ilay remote file {targets}", action="store_true")
    args = parser.parse_args()

    if args.debug:
        test_ratsy()

    cmd = [ "rsync", "-Pua" ]
    if args.pull:
        sudo_fetch()
        cmd.append("{}/{}".format(REMOTE_HOME_REF, targets))
        cmd.append(".")
    else:
        cmd.append("--delete")
        cmd.append(targets)
        cmd.append(REMOTE_HOME_REF)

    subprocess.run(
            cmd,
            check=True,
            )

if __name__ == '__main__':
    main()
